// Generated by scripts/build-design-schema.mjs from shared/design-schema.json.
#pragma once
#include <stdbool.h>
#include <stdint.h>

typedef struct {
    int32_t titleOffset;
    int32_t nameY;
    int32_t titleSize;
    int32_t nameSize;
    int32_t titleWidth;
    int32_t nameWidth;
    int32_t textColor;
    int32_t mutedColor;
    int32_t scale;
} face_design_t;

typedef struct {
    int32_t x;
    int32_t offsetY;
    int32_t width;
    int32_t height;
    int32_t rowGap;
    int32_t padding;
    int32_t radius;
    int32_t titleY;
    int32_t valueOffset;
    int32_t barY;
    int32_t resetY;
    int32_t pillY;
    int32_t numberSize;
    int32_t titleSize;
    int32_t resetSize;
    int32_t barHeight;
    int32_t pillHeight;
    int32_t pillPadding;
    int32_t textColor;
    int32_t mutedColor;
    int32_t cardColor;
    int32_t trackColor;
    int32_t fillColor;
    int32_t lowColor;
    int32_t warnColor;
    int32_t barStyle;
    int32_t barPixelSize;
    int32_t barPixelGap;
} usage_design_t;

typedef struct {
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    int32_t gap;
    int32_t padding;
    int32_t radius;
    int32_t senderY;
    int32_t subjectY;
    int32_t senderSize;
    int32_t subjectSize;
    int32_t lines;
    int32_t rows;
    int32_t textColor;
    int32_t mutedColor;
    int32_t cardColor;
} hey_design_t;

typedef struct {
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t dayY;
    int32_t timeSize;
    int32_t daySize;
    int32_t align;
    int32_t textColor;
    int32_t mutedColor;
} clock_design_t;

typedef struct {
    int32_t artY;
    int32_t artSize;
    int32_t artRadius;
    int32_t titleY;
    int32_t titleSize;
    int32_t artistY;
    int32_t artistSize;
    int32_t controlsY;
    int32_t controlSize;
    int32_t gap;
    int32_t textColor;
    int32_t mutedColor;
    int32_t accentColor;
    int32_t animateArtwork;
    int32_t spinArtwork;
} roon_design_t;

typedef struct {
    int32_t titleY;
    int32_t titleSize;
    int32_t valueY;
    int32_t valueSize;
    int32_t deviceY;
    int32_t deviceSize;
    int32_t controlsY;
    int32_t controlSize;
    int32_t gap;
    int32_t textColor;
    int32_t mutedColor;
} audio_design_t;

typedef union {
    face_design_t face;
    usage_design_t usage;
    hey_design_t hey;
    clock_design_t clock;
    roon_design_t roon;
    audio_design_t audio;
    int32_t values[28];
} module_design_t;

static inline unsigned module_design_length(unsigned kind)
{
    switch (kind) {
        case 0: return 9;
        case 1: return 28;
        case 2: return 16;
        case 3: return 9;
        case 4: return 15;
        case 5: return 11;
        default: return 0;
    }
}

static inline void module_design_default(unsigned kind, module_design_t *out)
{
    *out = (module_design_t){0};
    switch (kind) {
        case 0: out->face = (face_design_t){
            .titleOffset = 0,
            .nameY = 395,
            .titleSize = 24,
            .nameSize = 16,
            .titleWidth = 340,
            .nameWidth = 260,
            .textColor = 15920634,
            .mutedColor = 8287884,
            .scale = 100,
        }; break;
        case 1: out->usage = (usage_design_t){
            .x = 63,
            .offsetY = 0,
            .width = 340,
            .height = 150,
            .rowGap = -8,
            .padding = 16,
            .radius = 16,
            .titleY = 15,
            .valueOffset = 0,
            .barY = 98,
            .resetY = 113,
            .pillY = 48,
            .numberSize = 57,
            .titleSize = 16,
            .resetSize = 16,
            .barHeight = 10,
            .pillHeight = 28,
            .pillPadding = 11,
            .textColor = 15920634,
            .mutedColor = 9800868,
            .cardColor = 1381653,
            .trackColor = 2829099,
            .fillColor = 6668684,
            .lowColor = 15238019,
            .warnColor = 14269825,
            .barStyle = 0,
            .barPixelSize = 4,
            .barPixelGap = 2,
        }; break;
        case 2: out->hey = (hey_design_t){
            .x = 63,
            .y = 85,
            .width = 340,
            .height = 136,
            .gap = 12,
            .padding = 16,
            .radius = 16,
            .senderY = 12,
            .subjectY = 56,
            .senderSize = 28,
            .subjectSize = 28,
            .lines = 2,
            .rows = 2,
            .textColor = 15920634,
            .mutedColor = 9800868,
            .cardColor = 1381653,
        }; break;
        case 3: out->clock = (clock_design_t){
            .x = 33,
            .y = 155,
            .width = 400,
            .dayY = 308,
            .timeSize = 128,
            .daySize = 22,
            .align = 1,
            .textColor = 15920634,
            .mutedColor = 9800868,
        }; break;
        case 4: out->roon = (roon_design_t){
            .artY = 70,
            .artSize = 190,
            .artRadius = 16,
            .titleY = 280,
            .titleSize = 28,
            .artistY = 316,
            .artistSize = 21,
            .controlsY = 358,
            .controlSize = 64,
            .gap = 12,
            .textColor = 15920634,
            .mutedColor = 9800868,
            .accentColor = 6668684,
            .animateArtwork = 0,
            .spinArtwork = 0,
        }; break;
        case 5: out->audio = (audio_design_t){
            .titleY = 85,
            .titleSize = 24,
            .valueY = 130,
            .valueSize = 128,
            .deviceY = 300,
            .deviceSize = 22,
            .controlsY = 358,
            .controlSize = 64,
            .gap = 12,
            .textColor = 15920634,
            .mutedColor = 9800868,
        }; break;
    }
}

static inline bool module_design_valid(unsigned kind, unsigned field, int32_t value)
{
    switch (kind) {
        case 0: switch (field) {
            case 0: return (value >= -100 && value <= 40);
            case 1: return (value >= 260 && value <= 430);
            case 2: return (value >= 12 && value <= 48);
            case 3: return (value >= 12 && value <= 48);
            case 4: return (value >= 180 && value <= 420);
            case 5: return (value >= 160 && value <= 380);
            case 6: return (value >= 0 && value <= 16777215);
            case 7: return (value >= 0 && value <= 16777215);
            case 8: return (value >= 50 && value <= 150);
            default: return false;
        }
        case 1: switch (field) {
            case 0: return (value >= 20 && value <= 160);
            case 1: return (value >= -60 && value <= 60);
            case 2: return (value >= 180 && value <= 426);
            case 3: return (value >= 110 && value <= 190);
            case 4: return (value >= -8 && value <= 40);
            case 5: return (value >= 4 && value <= 40);
            case 6: return (value >= 0 && value <= 40);
            case 7: return (value >= 0 && value <= 80);
            case 8: return (value >= -20 && value <= 30);
            case 9: return (value >= 60 && value <= 150);
            case 10: return (value >= 90 && value <= 166);
            case 11: return (value >= 20 && value <= 100);
            case 12: return value == 0 || (value >= 24 && value <= 160);
            case 13: return (value >= 12 && value <= 48);
            case 14: return (value >= 12 && value <= 48);
            case 15: return (value >= 2 && value <= 24);
            case 16: return (value >= 24 && value <= 44);
            case 17: return (value >= 4 && value <= 24);
            case 18: return (value >= 0 && value <= 16777215);
            case 19: return (value >= 0 && value <= 16777215);
            case 20: return (value >= 0 && value <= 16777215);
            case 21: return (value >= 0 && value <= 16777215);
            case 22: return (value >= 0 && value <= 16777215);
            case 23: return (value >= 0 && value <= 16777215);
            case 24: return (value >= 0 && value <= 16777215);
            case 25: return value == 0 || value == 1 || value == 2;
            case 26: return (value >= 2 && value <= 16);
            case 27: return (value >= 0 && value <= 8);
            default: return false;
        }
        case 2: switch (field) {
            case 0: return (value >= 20 && value <= 160);
            case 1: return (value >= 20 && value <= 200);
            case 2: return (value >= 180 && value <= 426);
            case 3: return (value >= 80 && value <= 180);
            case 4: return (value >= 0 && value <= 60);
            case 5: return (value >= 4 && value <= 40);
            case 6: return (value >= 0 && value <= 40);
            case 7: return (value >= 0 && value <= 50);
            case 8: return (value >= 24 && value <= 100);
            case 9: return (value >= 12 && value <= 48);
            case 10: return (value >= 12 && value <= 48);
            case 11: return value == 1 || value == 2 || value == 3;
            case 12: return value == 1 || value == 2 || value == 3;
            case 13: return (value >= 0 && value <= 16777215);
            case 14: return (value >= 0 && value <= 16777215);
            case 15: return (value >= 0 && value <= 16777215);
            default: return false;
        }
        case 3: switch (field) {
            case 0: return (value >= 0 && value <= 160);
            case 1: return (value >= 40 && value <= 290);
            case 2: return (value >= 160 && value <= 466);
            case 3: return (value >= 100 && value <= 410);
            case 4: return (value >= 24 && value <= 160);
            case 5: return (value >= 12 && value <= 48);
            case 6: return value == 0 || value == 1 || value == 2;
            case 7: return (value >= 0 && value <= 16777215);
            case 8: return (value >= 0 && value <= 16777215);
            default: return false;
        }
        case 4: switch (field) {
            case 0: return (value >= 0 && value <= 340);
            case 1: return (value >= 80 && value <= 300);
            case 2: return (value >= 0 && value <= 80);
            case 3: return (value >= 0 && value <= 430);
            case 4: return (value >= 12 && value <= 48);
            case 5: return (value >= 0 && value <= 430);
            case 6: return (value >= 12 && value <= 48);
            case 7: return (value >= 0 && value <= 420);
            case 8: return (value >= 28 && value <= 72);
            case 9: return (value >= 8 && value <= 50);
            case 10: return (value >= 0 && value <= 16777215);
            case 11: return (value >= 0 && value <= 16777215);
            case 12: return (value >= 0 && value <= 16777215);
            case 13: return value == 0 || value == 1;
            case 14: return value == 0 || value == 1;
            default: return false;
        }
        case 5: switch (field) {
            case 0: return (value >= 0 && value <= 430);
            case 1: return (value >= 12 && value <= 48);
            case 2: return (value >= 0 && value <= 300);
            case 3: return (value >= 24 && value <= 160);
            case 4: return (value >= 0 && value <= 430);
            case 5: return (value >= 12 && value <= 48);
            case 6: return (value >= 0 && value <= 420);
            case 7: return (value >= 28 && value <= 72);
            case 8: return (value >= 8 && value <= 50);
            case 9: return (value >= 0 && value <= 16777215);
            case 10: return (value >= 0 && value <= 16777215);
            default: return false;
        }
        default: return false;
    }
}
