// Generated by scripts/build-reicon-icons.mjs. Do not edit.
#pragma once
#include "lvgl.h"

#define REICON_MASK_SIDE 128

extern const lv_image_dsc_t reicon_previous;
extern const lv_image_dsc_t reicon_next;
extern const lv_image_dsc_t reicon_play;
